<?php

/**
 * @file
 * Functions to support theming in the AQ Theme.
 */

/**
 * Implements hook_preprocess_html().
 */
function aq_theme_preprocess_html(&$variables) {
  // Aggiungi classe per Light/Dark mode
  $variables['attributes']['class'][] = 'theme-mode--light';
}

/**
 * Implements hook_preprocess_page().
 */
function aq_theme_preprocess_page(&$variables) {
  // Aggiungi variabili per il layout
  $variables['logo'] = theme_get_setting('logo');
  $variables['site_name'] = theme_get_setting('site_name');
  $variables['site_slogan'] = theme_get_setting('site_slogan');
} 